import copy
import importlib.util
import json
import unittest

from fpga.reference import stream27_context_transport11_prp_native as recipe


class OwnTransportPrp(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.manifest, cls.files, cls.bundle, cls.identifier = recipe.role()
        cls.asset = cls.files[recipe.ASSET].decode()
        cls.oracle = json.loads(cls.asset)

    def test_exact_captured_graph_frozen_cpp_oracle_and_calendar(self):
        old = json.loads((recipe.CAPTURE/'production-bundle.json').read_bytes())
        self.assertEqual(self.bundle, old)
        self.assertEqual(len(old['files']), 58)
        self.assertEqual(self.manifest['build']['sv_sources'], ['rtl/'+n for n in old['rtl_sources']])
        for name, text in old['files'].items():
            self.assertEqual(self.files['rtl/'+name], text.encode())
        self.assertEqual(recipe.sha(self.files[recipe.CPP]), recipe.CPP_PIN)
        self.assertEqual(recipe.sha(self.files[recipe.ASSET]), recipe.ORACLE_PIN)
        header = self.files[recipe.HEADER].decode()
        self.assertIn('INTERVAL=217,CARRY_DONE=217', header)
        self.assertIn('FIRST[2]={204,312}', header)
        self.assertNotIn('INTERVAL=214', header)
        self.assertIn(self.bundle['top'], header)
        self.assertEqual(self.identifier, recipe.NORMAL_ID)
        self.assertFalse(self.manifest['transport11_prp']['ancestor_results_inherited'])
        self.assertFalse(self.manifest['transport11_prp']['host_gl_implemented'])

    def test_full_exponents_and_same_dut_sentinel_recipe(self):
        # Existing encoded exponents are inspected, never regenerated by role().
        self.assertEqual(sum(c['steps'] for c in self.oracle['cases']), 41089)
        self.assertEqual(sum(c['doubles'] for c in self.oracle['cases']), 15137)
        for row in self.oracle['cases']:
            self.assertEqual(len(row['exponent_bits']), row['steps'])
            self.assertEqual(row['exponent_bits'].count('1'), row['doubles'])
            self.assertEqual(int(row['exponent_bits'], 2), row['base']**256)
        self.assertEqual(self.oracle['sentinel']['initial_impulse_address'], 128)
        self.assertEqual(self.oracle['sentinel']['expected_digits'], [-1]+[0]*255)
        cpp = self.files[recipe.CPP].decode()
        self.assertEqual(cpp.count('DUT d(&context)'), 1)
        self.assertLess(cpp.index('gfn16_runtime::configure(context,argc,argv)'), cpp.index('DUT d(&context)'))
        for guard in ('sentinel?N/2:0', 'N+4', 'sentinel?10u:9u', 'uint16_t(EPOCHS[c]+count(ci)-1)', 'next==counts'):
            self.assertIn(guard, cpp)

    def output(self):
        rows = []
        for index in range(10):
            wanted = self.oracle['cases'][index] if index < 8 else dict(base=recipe.BASES[index-8],steps=1,doubles=0,expected_digits=[-1]+[0]*255)
            rows.append(dict(case=index,base=wanted['base'],steps=wanted['steps'],doubles=wanted['doubles'],
                done_edge=recipe.FIRST[index%2]+(wanted['steps']-1)*217+218+10*256+20,
                sentinel=index>=8,digits=wanted['expected_digits']))
        text = recipe.LABEL+'\n'+'\n'.join('A_CONTEXT_PRP_RESULT '+json.dumps(r,separators=(',',':')) for r in rows)
        return text+'\nA_CONTEXT_PRP_PASS cases=8 sentinel_cases=2 squares=41091 doubles=15137 signed96_words=2560 interval=217\n'

    def test_standalone_validator_and_wrong_calendar_source_output_negatives(self):
        config = dict(family='R11',mode='normal',oracle_sha256=recipe.ORACLE_PIN)
        assets = dict(oracle=self.asset)
        text = self.output()
        self.assertEqual(recipe.validate(text,'',0,config,assets)['squares'], 41091)
        for bad in (text.replace('interval=217', 'interval=214'), text.replace('"case":0', '"case":1', 1),
                    text.replace('"sentinel":true', '"sentinel":false', 1), text.replace('"digits":[', '"digits":[true,', 1),
                    text+'extra\n', text.replace(recipe.LABEL, 'protected R11'), text.replace('"steps":', '"ignored":', 1)):
            with self.assertRaises(ValueError): recipe.validate(bad,'',0,config,assets)
        for mode in ('negative-comparator', 'negative-schedule'):
            negative = dict(config,mode=mode)
            value = recipe.validate(recipe.LABEL+'\n', 'A_PRP_RESIDUE_MISMATCH case=0 digit=0\n', 1, negative, assets)
            self.assertFalse(value['promotion_allowed'])
            with self.assertRaises(ValueError): recipe.validate(recipe.LABEL+'\n','',0,negative,assets)
        spec = importlib.util.spec_from_file_location('standalone_r11_prp_validator', recipe.ROOT/recipe.SELF)
        standalone = importlib.util.module_from_spec(spec); spec.loader.exec_module(standalone)
        self.assertEqual(standalone.validate(text,'',0,config,assets), recipe.validate(text,'',0,config,assets))
        with self.assertRaises(ValueError): recipe.validate(text,'',0,dict(config,family='R10'),assets)
        with self.assertRaises(ValueError): recipe.validate(text,'',0,config,dict(oracle=self.asset+' '))

    def test_separate_controls_source_equality_and_source_pin_refusal(self):
        manifest, files, bundle, identifier = recipe.role(True)
        self.assertEqual(bundle, self.bundle)
        self.assertEqual(files, self.files)
        self.assertEqual(manifest['test_role'], 'deliberate_fault')
        self.assertEqual(len(manifest['steps']), 2)
        self.assertTrue(all(s['expected_returncode'] == 1 for s in manifest['steps']))
        self.assertEqual(identifier, 's4-p16-c2-r11-prp-controls-q1-v1')
        with self.assertRaises(ValueError): recipe.role(1)
        pin = recipe.CAPTURE_BUNDLE
        try:
            recipe.CAPTURE_BUNDLE = '0'*64
            with self.assertRaises(ValueError): recipe.role()
        finally: recipe.CAPTURE_BUNDLE = pin


if __name__ == '__main__': unittest.main()
