"""Observed Azure budget/profile binding over the frozen finite class package.

Budget is checked before destination effects and again at execution. The exact
original role source/config identity is separate from appended shared helpers.
Host time is metered once; no per-job budget ledger or dispatcher is introduced.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import types

HERE=Path(__file__).resolve().parent
PARENT_SHA='61ae733fbd269a040aa73f02cf1d86810216fba24b57dc9ab4d8aade896a4932'
EXECUTOR_SHA='5a3ab8b8306e74de9d6dd9fcbe26ee185a25dff95ac6a5e1b51503ce00e543c3'
METER_SHA='b0875ec8fb12780c637548e9664d25d47a2b77bb8ef7d3ff997bbdfc640a8c9e'


def need(ok,why):
    if not ok:raise ValueError(why)


def meter():
    path=HERE.parent/'cloud/host_hours_azure_v2.py'
    need(hashlib.sha256(path.read_bytes()).hexdigest()==METER_SHA,'exact Azure meter')
    spec=importlib.util.spec_from_file_location('_package_azure_meter',path)
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module);return module


def source_identity(manifest):
    members=manifest.get('budget_source_members',manifest['sources'])
    need(type(members) is dict and members and all(manifest['sources'].get(k)==v for k,v in members.items()),'budget role members in exact closure')
    value={key:manifest[key] for key in ('build','probe','steps')};value['sources']=members
    return hashlib.sha256(json.dumps(value,sort_keys=True,separators=(',',':'),allow_nan=False).encode()).hexdigest()


def binding(value,profile,manifest):
    host=profile['host']
    if host=='aethia':
        need(value==dict(provider='local',host='aethia',cloud_cost_usd=0) and type(value['cloud_cost_usd']) is int,'exact local aethia budget')
    elif host=='gfn16-pilot-c4d':need(value.get('provider')=='gcp','exact GCP host budget')
    elif host in ('gfn16-azure-f16','gfn16-azure-sim-f32'):
        need(value.get('provider')=='azure','Azure cannot borrow other provider budget')
        return meter().validate_budget(value,host,3715,source_sha256=source_identity(manifest),profile_sha256=profile['profile_sha256'])
    else:raise ValueError('unadmitted budget host')


def worker(budget):
    raw=(HERE/'native_class_package_v1.py').read_bytes()
    need(hashlib.sha256(raw).hexdigest()==PARENT_SHA,'frozen finite package source')
    text=raw.decode().replace('native_class_package_v1.py','native_class_package_v3.py').replace('native_class_v1.py','native_class_v2.py')
    text=text.replace('1a50703e0554575e323697a11d5bbf43778603f78b1c978406734d7678529516',EXECUTOR_SHA)
    outer=types.ModuleType('_azure_class_package_binding');outer.__file__=str(Path(__file__).resolve())
    exec(compile(text,str(HERE/'native_class_package_v1.py')+'[observed-Azure]','exec'),outer.__dict__)
    module=outer.worker()
    module.PINS['native_class_package_v1.py']=PARENT_SHA
    original_budget_check=module.budget_check
    if budget.get('provider')=='azure':
        checker=meter();checker.validate_budget(budget,budget['host'],3715)
        for name,pin in checker.evidence_pins(budget).items():
            need(name not in module.PINS or module.PINS[name]==pin,'budget/control pin collision')
            module.PINS[name]=pin
    def budget_check(value,now=None):
        if value.get('provider')=='azure':return meter().validate_budget(value,value['host'],3715,now=now)
        return original_budget_check(value,now)
    # Rebind just the existing two functions; retain their globals/claims/order.
    # Functions were generated by the exact frozen source adapter, so recover
    # that adapter's known text rather than introspecting unavailable files.
    static_raw=(HERE/'native_static_package_v1.py').read_bytes()
    need(hashlib.sha256(static_raw).hexdigest()=='92f87083f3b70a3d64110d18ac3ff89af0783c2c4d15ab7ed65bfd2b4f217693','frozen static package adapter')
    static_binding={'__name__':'_budget_static_source','__file__':str(HERE/'native_static_package_v1.py')}
    exec(compile(static_raw,'[frozen static adapter]','exec'),static_binding)
    adapted=static_binding['adapted_source']((HERE/'native_package_v1.py').read_bytes())
    adapted=adapted.replace('native_static_v1.py','native_class_v2.py').replace('native_static_package_v1.py','native_class_package_v3.py')
    changes=[('budget_binding(budget,profile)','budget_binding(budget,profile,original)'),
      ("budget_binding(ticket['budget'],profile)","budget_binding(ticket['budget'],profile,m)"),
      ('m=json.loads(json.dumps(original));m.update(',"m=json.loads(json.dumps(original));m['budget_source_members']=dict(original['sources']);m.update(")]
    for old,new in changes:
        need(adapted.count(old)==1,'unique budget binding source anchor');adapted=adapted.replace(old,new,1)
    namespace=dict(module.__dict__,STATIC_PINS=module.PINS,budget_binding=binding)
    exec(compile(adapted,str(HERE/'native_package_v1.py')+'[Azure-source-budget]','exec'),namespace)
    namespace['budget_check']=budget_check
    result=types.ModuleType('_azure_finite_worker');result.__dict__.update(namespace)
    return result


def prepare(manifest,source_root,profile,job_id,phase,out,budget):
    return worker(json.loads(budget.read_text())).prepare(manifest,source_root,profile,job_id,phase,out,budget)


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);commands=parser.add_subparsers(dest='command',required=True)
    prep=commands.add_parser('prepare')
    for name in ('manifest','source-root','output','budget'):prep.add_argument('--'+name,type=Path,required=True)
    prep.add_argument('--profile',required=True);prep.add_argument('--id',required=True);prep.add_argument('--phase',choices=('lint','run'),required=True)
    run=commands.add_parser('run');run.add_argument('--ticket',type=Path,required=True);run.add_argument('--ticket-sha256',required=True)
    args=parser.parse_args()
    if args.command=='prepare':result=prepare(args.manifest.resolve(),args.source_root.resolve(),args.profile,args.id,args.phase,args.output.resolve(),args.budget.resolve())
    else:
        need(hashlib.sha256(args.ticket.read_bytes()).hexdigest()==args.ticket_sha256,'ticket before budget data')
        result=worker(json.loads(args.ticket.read_text())['budget']).run(args.ticket,args.ticket_sha256)
    print(json.dumps(result,indent=2))
